packages:
  - internal/*
  - internal/lint-configs/*
  - packages/*
  - packages/@core/*
  - packages/@core/base/*
  - packages/@core/ui-kit/*
  - packages/effects/*
  - scripts/*
  - apps/*
catalog:
  "@changesets/changelog-github": ^0.5.1
  "@changesets/cli": ^2.29.5
  "@changesets/git": ^3.0.4
  "@clack/prompts": ^0.9.1
  "@commitlint/cli": ^19.8.1
  "@commitlint/config-conventional": ^19.8.1
  "@ctrl/tinycolor": ^4.1.0
  "@eslint/js": ^9.31.0
  "@iconify/json": ^2.2.359
  "@iconify/tailwind": ^1.2.0
  "@iconify/vue": ^4.3.0
  "@intlify/core-base": ^9.14.5
  "@intlify/unplugin-vue-i18n": ^6.0.8
  "@jspm/generator": ^2.6.2
  "@manypkg/get-packages": ^2.2.2
  "@pnpm/workspace.read-manifest": ^1000.2.0
  "@stylistic/stylelint-plugin": ^3.1.3
  "@tailwindcss/nesting": 0.0.0-insiders.565cd3e
  "@tailwindcss/typography": ^0.5.16
  "@tanstack/vue-store": ^0.7.3
  "@types/archiver": ^6.0.3
  "@types/eslint": ^9.6.1
  "@types/html-minifier-terser": ^7.0.2
  "@types/jsonwebtoken": ^9.0.10
  "@types/lodash.clonedeep": ^4.5.9
  "@types/node": ^22.16.4
  "@types/nprogress": ^0.2.3
  "@types/postcss-import": ^14.0.3
  "@types/qrcode": ^1.5.5
  "@types/qs": ^6.14.0
  "@types/sortablejs": ^1.15.8
  "@typescript-eslint/eslint-plugin": ^8.37.0
  "@typescript-eslint/parser": ^8.37.0
  "@vee-validate/zod": ^4.15.1
  "@vitejs/plugin-vue": ^5.2.4
  "@vitejs/plugin-vue-jsx": ^4.2.0
  "@vue/shared": ^3.5.17
  "@vueuse/core": ^13.5.0
  "@vueuse/integrations": ^13.5.0
  archiver: ^7.0.1
  autoprefixer: ^10.4.21
  axios: ^1.10.0
  axios-mock-adapter: ^2.1.0
  cac: ^6.7.14
  chalk: ^5.4.1
  cheerio: ^1.1.0
  circular-dependency-scanner: ^2.3.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  commitlint-plugin-function-rules: ^4.0.2
  consola: ^3.4.2
  cross-env: ^7.0.3
  cspell: ^8.19.4
  cssnano: ^7.1.0
  cz-git: ^1.12.0
  czg: ^1.12.0
  dayjs: ^1.11.13
  defu: ^6.1.4
  depcheck: ^1.4.7
  dotenv: ^16.6.1
  element-plus: ^2.10.4
  eslint: ^9.31.0
  eslint-config-turbo: ^2.5.4
  eslint-plugin-command: ^0.2.7
  eslint-plugin-eslint-comments: ^3.2.0
  eslint-plugin-import-x: ^4.16.1
  eslint-plugin-jsdoc: ^50.8.0
  eslint-plugin-jsonc: ^2.20.1
  eslint-plugin-n: ^17.21.0
  eslint-plugin-no-only-tests: ^3.3.0
  eslint-plugin-perfectionist: ^4.15.0
  eslint-plugin-prettier: ^5.5.1
  eslint-plugin-regexp: ^2.9.0
  eslint-plugin-unicorn: ^56.0.1
  eslint-plugin-unused-imports: ^4.1.4
  eslint-plugin-vitest: ^0.5.4
  eslint-plugin-vue: ^9.33.0
  execa: ^9.6.0
  find-up: ^7.0.0
  get-port: ^7.1.0
  globals: ^15.15.0
  h3: ^1.15.3
  html-minifier-terser: ^7.2.0
  husky: ^9.1.7
  jsonc-eslint-parser: ^2.4.0
  jsonwebtoken: ^9.0.2
  lefthook: ^1.12.2
  less: ^4.3.0
  lint-staged: ^15.5.2
  lodash.clonedeep: ^4.5.0
  lucide-vue-next: ^0.469.0
  naive-ui: ^2.42.0
  nitropack: ^2.12.0
  nprogress: ^0.2.0
  ora: ^8.2.0
  pinia: ^3.0.3
  pinia-plugin-persistedstate: ^4.4.1
  pkg-types: ^1.3.1
  postcss: ^8.5.6
  postcss-antd-fixes: ^0.2.0
  postcss-html: ^1.8.0
  postcss-import: ^16.1.1
  postcss-load-config: ^6.0.1
  postcss-preset-env: ^10.2.4
  postcss-scss: ^4.0.9
  prettier: ^3.6.2
  prettier-plugin-tailwindcss: ^0.6.14
  publint: ^0.2.12
  qrcode: ^1.5.4
  qs: ^6.14.0
  radix-vue: ^1.9.17
  rimraf: ^6.0.1
  rollup: ^4.45.1
  rollup-plugin-visualizer: ^5.14.0
  sass: ^1.89.2
  secure-ls: ^2.0.0
  sortablejs: ^1.15.6
  stylelint: ^16.21.1
  stylelint-config-recess-order: ^5.1.1
  stylelint-config-recommended: ^14.0.1
  stylelint-config-recommended-scss: ^14.1.0
  stylelint-config-recommended-vue: ^1.6.1
  stylelint-config-standard: ^36.0.1
  stylelint-order: ^6.0.4
  stylelint-prettier: ^5.0.3
  stylelint-scss: ^6.12.1
  tailwind-merge: ^2.6.0
  tailwindcss: ^3.4.17
  tailwindcss-animate: ^1.0.7
  theme-colors: ^0.1.0
  turbo: ^2.5.4
  typescript: ^5.8.3
  unbuild: ^3.5.0
  unplugin-element-plus: ^0.8.0
  vee-validate: ^4.15.1
  vite: ^6.3.5
  vite-plugin-compression: ^0.5.1
  vite-plugin-dts: ^4.5.4
  vite-plugin-html: ^3.2.2
  vite-plugin-lazy-import: ^1.0.7
  vite-plugin-pwa: ^0.21.2
  vite-plugin-vue-devtools: ^7.7.7
  vue: ^3.5.17
  vue-eslint-parser: ^9.4.3
  vue-i18n: ^11.1.10
  vue-router: ^4.5.1
  zod: ^3.25.76
  zod-defaults: ^0.1.3
