packages:
    - internal/*
    - internal/lint-configs/*
    - packages/*
    - packages/@core/base/*
    - packages/@core/*
    - scripts/*
    - apps/*
catalog:
    "@changesets/git": ^3.0.1
    "@clack/prompts": ^0.7.0
    "@commitlint/cli": ^19.5.0
    "@commitlint/config-conventional": ^19.5.0
    "@eslint/js": ^9.10.0
    "@intlify/core-base": ^9.14.1
    "@intlify/unplugin-vue-i18n": ^5.2.0
    "@manypkg/get-packages": ^2.2.2
    "@stylistic/stylelint-plugin": ^3.0.1
    "@types/archiver": ^6.0.2
    "@types/chalk": ^2.2.0
    "@types/eslint": ^9.6.1
    "@types/lodash.clonedeep": ^4.5.9
    "@types/node": ^22.5.5
    "@types/sortablejs": ^1.15.8
    "@typescript-eslint/eslint-plugin": ^8.6.0
    "@typescript-eslint/parser": ^8.6.0
    "@vitejs/plugin-vue": ^5.1.4
    "@vitejs/plugin-vue-jsx": ^4.0.1
    "@vueuse/core": ^11.1.0
    archiver: ^7.0.1
    autoprefixer: ^10.4.20
    cac: ^6.7.14
    chalk: ^5.3.0
    commitlint-plugin-function-rules: ^4.0.0
    consola: ^3.2.3
    cross-env: ^7.0.3
    cspell: ^8.14.4
    cz-git: ^1.9.4
    czg: ^1.9.4
    dayjs: ^1.11.13
    dotenv: ^16.4.5
    element-plus: ^2.8.3
    eslint: ^9.10.0
    eslint-config-prettier: ^9.1.0
    eslint-config-turbo: ^2.1.2
    eslint-plugin-command: ^0.2.5
    eslint-plugin-eslint-comments: ^3.2.0
    eslint-plugin-import-x: ^4.2.1
    eslint-plugin-jsdoc: ^50.2.4
    eslint-plugin-jsonc: ^2.16.0
    eslint-plugin-n: ^17.10.3
    eslint-plugin-no-only-tests: ^3.3.0
    eslint-plugin-perfectionist: ^3.6.0
    eslint-plugin-prettier: ^5.2.1
    eslint-plugin-regexp: ^2.6.0
    eslint-plugin-unicorn: ^55.0.0
    eslint-plugin-unused-imports: ^4.1.4
    eslint-plugin-vitest: ^0.5.4
    eslint-plugin-vue: ^9.28.0
    execa: ^9.4.0
    find-up: ^7.0.0
    globals: ^15.9.0
    husky: ^9.1.6
    jsonc-eslint-parser: ^2.4.0
    less: ^4.2.0
    lint-staged: ^15.2.10
    lodash.clonedeep: ^4.5.0
    naive-ui: ^2.40.0
    nanoid: ^5.0.7
    nitropack: ^2.9.7
    ora: ^8.1.0
    pinia: ^2.2.2
    pinia-plugin-persistedstate: ^4.0.2
    pkg-types: ^1.2.0
    postcss: ^8.4.47
    postcss-html: ^1.7.0
    postcss-scss: ^4.0.9
    prettier: ^3.3.3
    prettier-plugin-tailwindcss: ^0.6.6
    radix-vue: ^1.9.6
    rimraf: ^6.0.1
    rollup-plugin-visualizer: ^5.12.0
    sass: ^1.79.3
    sortablejs: ^1.15.3
    stylelint: ^16.9.0
    stylelint-config-recess-order: ^5.1.0
    stylelint-config-recommended: ^14.0.1
    stylelint-config-recommended-scss: ^14.1.0
    stylelint-config-recommended-vue: ^1.5.0
    stylelint-config-standard: ^36.0.1
    stylelint-order: ^6.0.4
    stylelint-prettier: ^5.0.2
    stylelint-scss: ^6.6.6
    turbo: ^2.1.1
    typescript: ^5.6.2
    unbuild: ^2.0.0
    unplugin-element-plus: ^0.8.0
    vite: ^5.4.8
    vite-plugin-dts: ^4.2.2
    vite-plugin-html: ^3.2.2
    vite-plugin-lib-inject-css: ^2.1.1
    vite-plugin-pwa: ^0.20.5
    vite-plugin-vue-devtools: ^7.4.6
    vue: ^3.5.10
    vue-eslint-parser: ^9.4.3
    vue-i18n: ^10.0.3
    vue-router: ^4.4.5
